apiVersion: v1
kind: Service
metadata:
    name: accessyouthapi
spec:
    ports:
        - port: 80
          targetPort: 3000 
          protocol: TCP
    selector:
        name: accessyouthapi
    type: LoadBalancer